### ISSUE TITLE
Implement the new style system

### ISSUE THREAD

**Issue by ghost** [vizia/vizia#170]
A tracking issue for the work on the new [style system](https://github.com/vizia/style_system).

# Tracking issue

## Style system

- [ ] Add keyframe animations.
- [ ] Add custom properties.
- [ ] Add all/most of the properties we need and want.
- [ ] Combine the selectors and property parsing.
- [ ] Add tests for the selectors.
- [ ] Write tests for parsing whole style sheets.
- [ ] Test some real world examples to see if everything behaves properly.
- [ ] Implement it in vizia (Maybe in a separate crate?)

## Vizia

- [ ] Add support for properties that vizia currently can't represent (border, outline, ...).

# Properties

<details>
<summary>List of properties</summary>

## Note

Every property marked with a `*` means that the property could be implemented by the new style system, but vizia doesn't support it currently.

## TODOs

- [x] ~~Remove `selection-color` once we have the pseudoselector version.~~ Added a TODO note in the code.
- [x] Change `border-corner-shape` to support defining all four sides.
- [x] Remove `inset` property from `BoxShadow`.
- [x] Fix spelling mistake in `inner-shadow-blur` property.
- [x] Add separate `translate`, `rotate` and `scale` properties that use the `Transform` type.

## General

- [x] display
- [x] visibility
- [x] overflow
- [x] opacity

## Layout

- [x] layout-type
- [x] position-type
- [x] space
- [x] left
- [x] width
- [x] right
- [x] top
- [x] height
- [x] bottom
- [x] min-left
- [x] max-left
- [x] min-width
- [x] max-width
- [x] min-right
- [x] max-right
- [x] min-top
- [x] max-top
- [x] min-height
- [x] max-height
- [x] min-bottom
- [x] max-bottom
- [x] child-space
- [x] child-left
- [x] child-right
- [x] child-top
- [x] child-bottom
- [x] row-between
- [x] col-between

### Shorthand

- [ ] border*

### Color

- [x] border-color*
- [ ] border-top-color*
- [ ] border-right-color*
- [ ] border-bottom-color*
- [ ] border-left-color*

### Shape

- [x] border-corner-shape
- [x] border-top-left-shape
- [x] border-top-right-shape
- [x] border-bottom-left-shape
- [x] border-bottom-right-shape

### Radius

- [x] border-radius
- [x] border-top-left-radius
- [x] border-top-right-radius
- [x] border-bottom-left-radius
- [x] border-bottom-right-radius

### Style

- [ ] border-style*
- [ ] border-top-style*
- [ ] border-right-style*
- [ ] border-bottom-style*
- [ ] border-left-style*

### Width

- [x] border-width
- [x] border-top-width
- [x] border-right-width
- [x] border-bottom-width
- [x] border-left-width

### Shorthand

- [ ] outline*

### Color

- [x] outline-color*
- [ ] outline-top-color*
- [ ] outline-right-color*
- [ ] outline-bottom-color*
- [ ] outline-left-color*

### Style

- [ ] outline-style*
- [ ] outline-top-style*
- [ ] outline-right-style*
- [ ] outline-bottom-style*
- [ ] outline-left-style*

### Width

- [x] outline-width
- [x] outline-top-width
- [x] outline-right-width
- [x] outline-bottom-width
- [x] outline-left-width

## Background

- [x] background-color
- [x] background-image
- [ ] background-gradient

## Font

- [x] font-size
- [x] font-color
- [ ] font-weight
- [x] font
- [x] selection-color
- [x] caret-color
- [ ] caret-shape
- [ ] user-select
- [x] text-wrap

### Outer

- [x] outer-shadow
- [x] outer-shadow-h-offset
- [x] outer-shadow-v-offset
- [x] outer-shadow-blur
- [x] outer-shadow-color

### Inner

- [x] inner-shadow
- [x] inner-shadow-h-offset
- [x] inner-shadow-v-offset
- [x] inner-shadow-blur
- [x] inner-shadow-color

## Other

- [x] transition
- [x] z-index
- [x] transform
- [x] cursor

## Custom

- [ ] custom property support

</details>

# Selectors

<details>
<summary>List of selectors</summary>

## Combinator

- [ ] Child (>)
- [ ] Descendant (space)
- [ ] NextSibling (+)
- [ ] LaterSibling (~)

## Identifier
- [ ] ID (#name)
- [ ] LocalName (element)
- [ ] Class (.class)

## PseudoClass
- [ ] FirstChild
- [ ] LastChild
- [ ] Root
- [ ] Hover
- [ ] Active
- [ ] Focus
- [ ] Enabled
- [ ] Disabled
- [ ] ReadOnly
- [ ] ReadWrite
- [ ] PlaceHolderShown
- [ ] Default
- [ ] Checked
- [ ] Indeterminate
- [ ] Blank
- [ ] Valid
- [ ] Invalid
- [ ] InRange
- [ ] OutOfRange
- [ ] Required
- [ ] Optional
- [ ] UserValid
- [ ] UserInvalid
- [ ] Lang
- [ ] Dir
- [ ] Custom

## PseudoElement
- [ ] After (::after)
- [ ] Before (::before)
- [ ] Selection (::selection)
- [ ] Custom
</detail>
